server:
  port: 8090
spring:
  application:
    name: provider-service
eureka:
  client:
    service-url:
      defaultZone: http://root:root@localhost:8080/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${eureka.instance.hostname}:${server.port}
